name: Generate Doxygen Documentation

on:
  push:
    branches:
      - dev
      - feat/github_pages

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Doxygen
        run: sudo apt-get install doxygen

      - name: Generate Documentation
        run: ./documentation.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
