name: Mirror main to Epitech Repo

on:
  push:
    branches: 
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ secrets.BENS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Push to Target Repository
        run: |
          git push --force git@github.com:EpitechPromo2026/B-CPP-500-BER-5-2-rtype-kentin.paille.git HEAD:main
