name: Mirror to Epitech repo

on:
  push:
    branches: 
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2

      - name: Push to Target Repository
        run: |
          git push https://${{secrets.PAT}}@git@github.com:EpitechPromo2026/B-CPP-500-BER-5-2-rtype-kentin.paille.git HEAD:main